if (CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(LIB_STATIC_EXT ".a")
    set(LIB_STATIC_EXT ".dylib")
    set(LIB_PREFIX "lib")
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(LIB_STATIC_EXT ".a")
    set(LIB_SHARED_EXT ".so")
    set(LIB_PREFIX "lib")

    if (TARGET_ARCH MATCHES "x64")
        set(LIB_STATIC_SUFFIX "")
    else()
        set(LIB_STATIC_SUFFIX "_i486")
    endif()
elseif(WIN32)
    set(LIB_STATIC_EXT ".lib")
    set(LIB_SHARED_EXT ".dll")
    set(LIB_STATIC_SUFFIX "")
    # If have WIN64 then do further things
endif()